## Installing Libraries

In [1]:
!pip install azure-storage-blob

Collecting azure-storage-blob
  Downloading azure_storage_blob-12.25.1-py3-none-any.whl.metadata (26 kB)
Collecting azure-core>=1.30.0 (from azure-storage-blob)
  Downloading azure_core-1.33.0-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.13.1)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core>=1.30.0->azure-storage-blob) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core>=1.30.0->azure-storage-blob) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=2.1.4->azure-storage-blob) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob) (2.22)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (2025.1.31)
Downloading azure_storage_blob-12.25.1-py3-none-any.whl (406 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.0/407.0 kB 15.5 MB/s eta 0:00:00
Downloading azure_core-1.33.0-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.1/207.1 kB 16.8 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Installing collected packages: isodate, azure-core, azure-storage-blob
Successfully installed azure-core-1.33.0 azure-storage-blob-12.25.1 isodate-0.7.2

## Importing Libraries

In [2]:
import os, uuid
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
import pandas as pd
import numpy as np
import json
import requests
import io

In [3]:
RESTAURANT_DOWNLOAD_URL = "https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?fourfour=43nn-pn8j&cacheBust=1744137254&date=20250408&accessType=DOWNLOAD"


response = requests.get(RESTAURANT_DOWNLOAD_URL)
df = pd.read_csv(io.StringIO(response.text))
df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location Point1
0,41708809,HL SPRING GARDEN,Brooklyn,8706,5 AVENUE,11209.0,7189217171,Chinese,04/25/2024,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.620745,-74.026869,310.0,43.0,16000.0,3153758.0,3.060500e+09,BK31,NaN
1,50018884,"DUNKIN', 'BASKIN ROBBINS",Queens,7302,AUSTIN ST,11375.0,7185750892,Donuts,03/27/2025,No violations were recorded at the time of thi...,...,Administrative Miscellaneous / Re-inspection,40.718246,-73.840370,406.0,29.0,76901.0,4078759.0,4.032910e+09,QN17,NaN
2,50063056,MASPETH CAFETERIA,Queens,4805,GRAND AVE,11378.0,2016388280,American,06/22/2023,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.717286,-73.919782,405.0,30.0,21900.0,4058955.0,4.026020e+09,QN31,NaN
3,50098565,TARIM UYGHUR CUISINE,Queens,136-20,ROOSEVELT AVENUE,11354.0,6193650179,Chinese,10/03/2024,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.759778,-73.829235,407.0,20.0,85300.0,4113546.0,4.050190e+09,QN22,NaN
4,50106079,EL PALENQUE TRES GALLOS,Brooklyn,816,AVENUE U,11223.0,6467446081,Mexican,07/26/2024,Violations were cited in the following area(s).,...,Cycle Inspection / Initial Inspection,40.598114,-73.962784,315.0,48.0,39200.0,3193142.0,3.071350e+09,BK25,NaN

In [9]:
RESTAURANT_DOWNLOAD_URL_JSON = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"
resp = requests.get(RESTAURANT_DOWNLOAD_URL_JSON)
data = resp.json()
df_json = pd.DataFrame(data)
print(df_json.shape)
df_json.head(25)
# 64571486

(1000, 46)

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,...,taxi_pick_up_location,vehicle_type,closed_date,resolution_description,facility_type,due_date,bridge_highway_name,bridge_highway_segment,bridge_highway_direction,road_ramp
0,64571486,2025-04-07T01:51:12.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10033,600 WEST 183 STREET,WEST 183 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,64570400,2025-04-07T01:51:01.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11233,541 CHAUNCEY STREET,CHAUNCEY STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64571430,2025-04-07T01:50:38.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10037,2300 5 AVENUE,5 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64571425,2025-04-07T01:49:56.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11233,519 CHAUNCEY STREET,CHAUNCEY STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,64576182,2025-04-07T01:49:26.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10460,1713 HOE AVENUE,HOE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,64570514,2025-04-07T01:48:37.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10474,710 HUNTS POINT AVENUE,HUNTS POINT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,64575354,2025-04-07T01:47:59.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10031,660 RIVERSIDE DRIVE,RIVERSIDE DRIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,64574535,2025-04-07T01:47:20.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11423,184-41 90 AVENUE,90 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,64571378,2025-04-07T01:47:12.000,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Non Passenger,NaN,11101,29-08 THOMSON AVENUE,THOMSON AVENUE,...,"29-08 THOMSON AVENUE, QUEENS (LONG ISLAND CITY...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,64571286,2025-04-07T01:46:39.000,DSNY,Department of Sanitation,Dirty Condition,Trash,Sidewalk,11432,86-86 MIDLAND PARKWAY,MIDLAND PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,64576330,2025-04-07T01:45:47.000,NYPD,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,Street/Sidewalk,10468,2608 CRESTON AVENUE,CRESTON AVENUE,...,NaN,Car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,64576409,2025-04-07T01:44:54.000,NYPD,New York City Police Department,Abandoned Vehicle,With License Plate,Street/Sidewalk,11374,98-59 62 ROAD,62 ROAD,...,NaN,SUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,64574293,2025-04-07T01:44:54.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10457,2082 VALENTINE AVENUE,VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,64574292,2025-04-07T01:44:17.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11368,55-02 98 STREET,98 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,64574388,2025-04-07T01:42:32.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11213,1196 EASTERN PARKWAY,EASTERN PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,64575322,2025-04-07T01:42:25.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,11212,230 LOTT AVENUE,LOTT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,64575346,2025-04-07T01:42:07.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10465,235 QUINCY AVENUE,QUINCY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,64571484,2025-04-07T01:42:05.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10025,951 AMSTERDAM AVENUE,AMSTERDAM AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,64572373,2025-04-07T01:39:12.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10309,2945 ARTHUR KILL ROAD,ARTHUR KILL ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,64576175,2025-04-07T01:38:02.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11201,175 ADAMS STREET,ADAMS STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,64573312,2025-04-07T01:38:01.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10462,2100 EAST TREMONT AVENUE,EAST TREMONT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,64573320,2025-04-07T01:38:01.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,11220,769 59 STREET,59 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,64575202,2025-04-07T01:37:54.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10309,2945 ARTHUR KILL ROAD,ARTHUR KILL ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,64570522,2025-04-07T01:37:42.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10128,312 EAST 95 STREET,EAST 95 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,64576338,2025-04-07T01:37:13.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10468,2454 WEBB AVENUE,WEBB AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
RESTAURANT_DOWNLOAD_URL_JSON = "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=10&$offset=15"
resp = requests.get(RESTAURANT_DOWNLOAD_URL_JSON)
data = resp.json()
df_json = pd.DataFrame(data)
print(df_json.shape)
df_json.head(25)

KeyboardInterrupt:

In [14]:
number_of_rows = 39570654
limit = 50000

for offset in range(0, number_of_rows, limit):
  RESTAURANT_DOWNLOAD_URL_JSON = f"https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit={limit}&$offset={offset}"
  print(RESTAURANT_DOWNLOAD_URL_JSON)
  resp = requests.get(RESTAURANT_DOWNLOAD_URL_JSON)
  data = resp.json()

https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=0
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=50000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=1950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=2950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=3950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=4950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=5950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=6950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=7950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=8950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=9950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=10950000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11000000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11050000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11100000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11150000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11200000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11250000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11300000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11350000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11400000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11450000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11500000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11550000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11600000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11650000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11700000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11750000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11800000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11850000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11900000
https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=50000&$offset=11950000